### ISSUE TITLE
Ska.ParseCM  and Ska.quatutil tests fail

### ISSUE THREAD

**Issue by javierggt** [sot/ska_testr#22]
The failure can be traced to the first line in test_unit_git.sh:
```
GIT=`PATH=/usr/bin:$PATH which git`
```
which sets GIT=/usr/bin/git instead of the git in the conda environment. This then fails in presto:
```
(ska3-flight) jgonzale ska_testr $ /usr/bin/git clone https://github.com/sot/Ska.ParseCM
Cloning into 'Ska.ParseCM'...
error: Unknown SSL protocol error in connection to github.com:443  while accessing https://github.com/sot/Ska.ParseCM/info/refs?service=git-upload-pack
fatal: HTTP request failed
```

Instead of fixing this script, I propose to fix those packages to install their corresponding test submodules, and to use testr.

**Comment by javierggt** [comment]
Ska.quatutil uses nose, and Ska.ParseCM uses unittest. Should those be changed to use pytest?

**Comment by jeanconn** [comment]
I would suggest feel free to update Ska.quatutil tests, but don't bother with Ska.ParseCM as it is a deprecated package.

I also don't generally run the SKA3_HEAD ska_testr profile from presto (and instead run the full tests from a CentOS6 or CentOS7 machine).

**Comment by javierggt** [comment]
Ok, I made the changes in the PR is in sot/Ska.quatutil/pull/7.

After that is merged, we need to change Ska.quatutil tests here.

**Comment by taldcroft** [comment]
With regards to Ska.ParseCM, I did a sot org search on Ska.ParseCM and there are three substantive uses of this package:
- https://github.com/sot/cmd_states/blob/b458249e5f17f3176d943a87dc13a0d6f8743696/Chandra/cmd_states/add_nonload_cmds.py#L106
- https://github.com/sot/cmd_states/blob/e8ad02fdbbf8b63e70f492705af19f8af6516ec3/Chandra/cmd_states/cmd_states.py#L533
- https://github.com/sot/star_stat_db/blob/32d1664339b516e6ee0e894bd6229c338806b55e/update_star_stats.py#L576

So while use of Ska.ParseCM for new code is deprecated, we are still using it in flight code (in particular cmd_states).  As long as that is true it is worth the effort to modernize the testing and keep it in the test suite.  Or else remove it from those three locations, but I don't think `parse_cm` is  quite a drop-in replacement so I'm not sure offhand about level of effort and how much we can trust existing unit testing.

**Comment by jeanconn** [comment]
Gotcha.  Maybe we can just review the cmd_states coverage?  I figured Ska.ParseCM might not need updated unit tests if deprecated *and* the flight use of it was already covered, but admit I did not look at the cmd_states testing.  I also haven't looked at what the cmd_states jobs need to move into skare3.

**Comment by taldcroft** [comment]
Yeah, all of that is somewhat uncertain LOE instead of just turning the crank and making tests work for Ska.ParseCM.

**Comment by taldcroft** [comment]
All tests passing now.
